### ISSUE TITLE
Connect issue

### ISSUE THREAD

**Issue by xing2387** [Souler/ppsspp-adhoc-server#1]
I wanna play "Gundam VS Gundam - Next Plus", 
and i have installed and running this server on my vps with centos7, 
and connected two ppsspp client, one on my win10 pc, one on my android phone.
Although the log shows their join the same room, their just can't see each other on the game...
Need help and thank very much for make this software for us.

This is the log:

> New Connection from 223.73.59.101.
PPSSPP (MAC: 7C:02:8E:01:13:87 - IP: 223.73.59.101) started playing NPJH50107.
PPSSPP (MAC: 7C:02:8E:01:13:87 - IP: 223.73.59.101) requested information on 0 NPJH50107 groups.
PPSSPP (MAC: 7C:02:8E:01:13:87 - IP: 223.73.59.101) joined NPJH50107 group GVSGPV00.
New Connection from 112.96.70.81.
PPSSPP (MAC: 5D:A1:B1:20:6C:60 - IP: 112.96.70.81) started playing NPJH50107.
PPSSPP (MAC: 5D:A1:B1:20:6C:60 - IP: 112.96.70.81) requested information on 1 NPJH50107 groups.
PPSSPP (MAC: 5D:A1:B1:20:6C:60 - IP: 112.96.70.81) joined NPJH50107 group GVSGPV00.

**Comment by xing2387** [comment]
sorry... my both of my devices are under the large LAN provided by the ISP, so they can't communicate with each other directly.
sorry again for my poor English...

**Comment by Souler** [comment]
Hi, yes. In for both clients to be able to communicate to each other, all 3 actors (server, client1 and client2) must be on the same network.

I don't have an active PPSSPP server anymore, but when I did I used to have a Ubuntu server running pptpd (a Windows VPN compatible server). Then both clients(both running in Windows) connected to the VPN via the windows private network UI.

Hope it helps!
